/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        String note = "The bird is red";
        String[] articles = {"I write a lot.", "To and fro"};

        boolean result = NoteBuilder.canCreateNote(note, articles);

        if(result){
            System.out.println("True");
        } else {
            System.out.println("False");
        }
    }
}
